// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for AuroraDatabaseCreateOwnerFunction
 */
export interface AuroraDatabaseCreateOwnerFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/funcs/aurora-database-create-owner.
 */
export class AuroraDatabaseCreateOwnerFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: AuroraDatabaseCreateOwnerFunctionProps) {
    super(scope, id, {
      description: 'src/funcs/aurora-database-create-owner.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/funcs/aurora-database-create-owner.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}