// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for CreateSchemaFunction
 */
export interface CreateSchemaFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/funcs/create-schema.
 */
export class CreateSchemaFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: CreateSchemaFunctionProps) {
    super(scope, id, {
      description: 'src/funcs/create-schema.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs24.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../assets/funcs/create-schema.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}